export const ADD_FRIEND = 'ADD_FRIEND';
export const INCREASE_COUNTER = 'INCREASE_COUNTER';
export const DECREASE_COUNTER = 'ADD_FRIEND';
export const GET_DATA = 'GET_DATA';
export const CREATE_CHANNEL = 'CREATE_CHANNEL';
export const FIRE_NOTIFICATION = 'FIRE_NOTIFICATION';
export const FIRE_SCHEDULE_NOTIFICATION = 'FIRE_SCHEDULE_NOTIFICATION';
export const CANCEL_ALL_NOTIFICATION = 'CANCEL_ALL_NOTIFICATION';